version: "3.8"

# Media servers
services:
  # Jellyfin - Open source media server
  jellyfin:
    image: ${JELLYFIN_IMAGE:-linuxserver/jellyfin}:${IMAGE_RELEASE:-latest}
    container_name: ${JELLYFIN_CONTAINER:-jellyfin}
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TIMEZONE:-UTC}
    volumes:
      - ${DOCKER_DIR:-$HOME/docker}/jellyfin:/config
      - ${MEDIA_DIR:-/mnt/media}:/media
    ports:
      - ${JELLYFIN_PORT:-8096}:8096
      - ${JELLYFIN_HTTPS_PORT:-8920}:8920
    restart: unless-stopped
    # Include hardware acceleration devices if available
    ${HW_ACCEL_JELLYFIN}
    networks:
      - app_network
    profiles:
      - jellyfin

  # Plex Media Server
  plex:
    image: ${PLEX_IMAGE:-linuxserver/plex}:${IMAGE_RELEASE:-latest}
    container_name: ${PLEX_CONTAINER:-plex}
    network_mode: host
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TIMEZONE:-UTC}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM:-}
    volumes:
      - ${DOCKER_DIR:-$HOME/docker}/plex:/config
      - ${MEDIA_DIR:-/mnt/media}/tv:/tv
      - ${MEDIA_DIR:-/mnt/media}/movies:/movies
      - ${MEDIA_DIR:-/mnt/media}/music:/music
      - ${MEDIA_DIR:-/mnt/media}/photos:/photos
    restart: unless-stopped
    # Include hardware acceleration devices if available
    ${HW_ACCEL_PLEX}
    profiles:
      - plex

  # Emby Media Server
  emby:
    image: ${EMBY_IMAGE:-linuxserver/emby}:${IMAGE_RELEASE:-latest}
    container_name: ${EMBY_CONTAINER:-emby}
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TIMEZONE:-UTC}
    volumes:
      - ${DOCKER_DIR:-$HOME/docker}/emby:/config
      - ${MEDIA_DIR:-/mnt/media}/tv:/tv
      - ${MEDIA_DIR:-/mnt/media}/movies:/movies
      - ${MEDIA_DIR:-/mnt/media}/music:/music
    ports:
      - ${EMBY_PORT:-8096}:8096
      - ${EMBY_HTTPS_PORT:-8920}:8920
    restart: unless-stopped
    # Include hardware acceleration devices if available
    ${HW_ACCEL_EMBY}
    networks:
      - app_network
    profiles:
      - emby